# Generated by Django 5.2.1 on 2026-09-03 05:07

import apps.users.models
import common.objectid
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', common.objectid.ObjectIdField(default=common.objectid.generate_object_id, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_image', models.CharField(blank=True, max_length=1024, null=True)),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'SUPER_ADMIN'), ('CLUB_OWNER', 'CLUB_OWNER'), ('TECH_DIRECTOR', 'TECH_DIRECTOR'), ('COORDINATOR', 'COORDINATOR'), ('COACH', 'COACH'), ('PLAYER', 'PLAYER'), ('PARENT', 'PARENT')], max_length=32)),
                ('is_first_login', models.BooleanField(default=True)),
                ('child_player_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True, default=list, size=None)),
                ('parent_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True, default=list, size=None)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club_id', models.ForeignKey(blank=True, db_column='club_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='members', to='clubs.club')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', apps.users.models.UserManager()),
            ],
        ),
    ]
