# Generated by Django 5.2.1 on 2026-09-03 05:07

import common.objectid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionRequest',
            fields=[
                ('id', common.objectid.ObjectIdField(default=common.objectid.generate_object_id, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('WAITING_ON_PARENT', 'WAITING_ON_PARENT'), ('WAITING_ON_CHILD', 'WAITING_ON_CHILD'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child_id', models.ForeignKey(db_column='child_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('club_id', models.ForeignKey(db_column='club_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clubs.club')),
                ('parent_id', models.ForeignKey(db_column='parent_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requester_id', models.ForeignKey(db_column='requester_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'connection_requests',
            },
        ),
    ]
