# Generated by Django 5.2.1 on 2026-09-03 05:07

import common.objectid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', common.objectid.ObjectIdField(default=common.objectid.generate_object_id, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club_id', models.ForeignKey(db_column='club_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='age_groups', to='clubs.club')),
                ('coordinator_id', models.ForeignKey(blank=True, db_column='coordinator_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'age_groups',
            },
        ),
    ]
