# Generated by Django 5.2.1 on 2026-09-03 05:07

import common.objectid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', common.objectid.ObjectIdField(default=common.objectid.generate_object_id, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club_id', models.ForeignKey(db_column='club_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='clubs.club')),
                ('created_by', models.ForeignKey(db_column='created_by', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('team_id', models.ForeignKey(db_column='team_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='teams.team')),
            ],
            options={
                'db_table': 'events',
            },
        ),
    ]
