# Generated by Django 5.2.1 on 2026-09-03 05:07

import common.objectid
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('age_groups', '0001_initial'),
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', common.objectid.ObjectIdField(default=common.objectid.generate_object_id, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('roster', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True, default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age_group_id', models.ForeignKey(db_column='age_group_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teams', to='age_groups.agegroup')),
                ('club_id', models.ForeignKey(db_column='club_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teams', to='clubs.club')),
                ('coach_id', models.ForeignKey(blank=True, db_column='coach_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teams',
            },
        ),
    ]
