# Generated by Django 5.2.1 on 2026-09-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
